import React from 'react';
import { Link } from 'react-router';

class Sidebar extends React.Component {
  render() {
    return (
      <div className="profile-sidebar">
        <div className="profile-userpic">
          {/*}<img src="/images/Naveed.jpeg" className="img-responsive" alt="" />*/}
        </div>
        <div className="profile-usertitle">
          <div className="profile-usertitle-name">
            Welcome {this.props.user && this.props.user.displayName}

          </div>
          <div className="profile-usertitle-email">
            {/*this.props.user && this.props.user.email*/}

          </div>
        </div>
        {/*
        <div className="profile-userbuttons">
          <Link to="/profile"><button type="button" className="btn btn-info btn-sm">Settings</button></Link>
          <Link to="/logout"><button type="button" className="btn btn-danger btn-sm">Logout</button></Link>
        </div>
        */}
        <div className="profile-usermenu">
        <ul className="nav">
            <li>
              <span>
                Number of reports generated this month: {this.props.stats && this.props.stats.totalUserTests}
              </span>
            </li>
            <li>
              <span>
                Total number of reports generated by clinicians: {this.props.stats && this.props.stats.totalTests}
              </span>
            </li>
          </ul>
        </div>
        <div className="profile-usermenu">
          <ul className="nav">
            <li>
              <Link activeClassName="active" to="/createform">
              <i className="glyphicon glyphicon-plus"></i>
              Create a report </Link>
            </li>
            <li>
              <Link activeClassName="active" to="/dashboard">
              <i className="glyphicon glyphicon-hourglass"></i>
              Pending reports </Link>
            </li>
            <li>
              <Link activeClassName="active" to="/viewrecords">
              <i className="glyphicon glyphicon-ok"></i>
              View completed reports </Link>
            </li>
            <div className="profile-userbuttons">
              <Link to="/profile"><button type="button" className="btn btn-info btn-sm">Settings</button></Link>
            </div>
            {/* <li>
              <Link activeClassName="active" to="#">
              <i className="glyphicon glyphicon-flag"></i>
              Help </Link>
            </li> */}
          </ul>
        </div>
        </div>
    )
  }
}

export default Sidebar;
